# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1513329cabbf53db87b183285dc8b64a1d01be2707adfb040bb30dd41b5a06a3ffb3032cbbf7ea110a31c8049237992cc3e318ff72f1fb7fa8e615491bcb434

test:
  secret_key_base: 989c8754b80b85462d3de27be4b1075d6cfd10d74462ab03ef0e4e540c4279890af5108ff27d0c129c64bb6251bec133c6ddf424d95c983a6cb1d4d450909d5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
